config/routes.rb
Rails.application.routes.draw do
  resources :parts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/part.rb
# == Schema Information
#
# Table name: parts
#
#  id                    :bigint           not null, primary key
#  ads_cost              :integer
#  name                  :string
#  supplier_parts_number :string
#  supplier_quote_number :string
#  unit_cost             :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#
class Part < ApplicationRecord
  after_create_commit { broadcast_prepend_to "parts" }
  after_update_commit { broadcast_replace_to "parts" }
  after_destroy_commit { broadcast_remove_to "part" }

  validates :name, :ads_cost, presence: true

  validate :quote_number_exists_if_part_number_present

  def quote_number_exists_if_part_number_present
    if supplier_quote_number.blank? && supplier_parts_number.present?
      errors.add(:supplier_quote_number, "Supplier quote number must exist for parts with supplier parts number")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all.each(&:valid?)
    @debug = params[:debug] == "true"
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to parts_url, notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_part
    @part = Part.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def part_params
    params.require(:part).permit(:name, :ads_cost, :supplier_parts_number, :supplier_quote_number, :unit_cost)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotWired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parts/_form.html.erb
<%= form_with(model: part) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    Name
    <%= form.text_field :name %>
    supplier_parts_number
    <%= form.text_field :supplier_parts_number %>
    supplier_quote_number
    <%= form.text_field :supplier_quote_number %>
    unit_cost
    <%= form.number_field :unit_cost %>
    ads_cost
    <%= form.number_field :ads_cost %>
    submit
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<%= turbo_frame_tag dom_id(part) do %>
  <div class="card m-4">
    <div class="card-body">
      <%= form_with(model: part) do |form| %>
        <% if @debug %>
          <%= part.errors.inspect %>
        <% end %>
        <% if part.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

            <ul>
              <% part.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if @debug %>
          <div><%= part.inspect %><div>
        <% end %>
        <div class="actions">
          Name
          <%= form.text_field :name %>
          supplier_parts_number
          <%= form.text_field :supplier_parts_number %>
          supplier_quote_number
          <%= form.text_field :supplier_quote_number %>
          unit_cost
          <%= form.number_field :unit_cost %>
          ads_cost
          <%= form.number_field :ads_cost %>
          <%= form.submit %>
          <%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/parts/edit.html.erb
<%= render 'part', part: @part %>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<div class="d-flex">
<table>
  <thead>
    <tr>
      <th colspan="9"></th>
    </tr>
  </thead>

  <tbody>
    <%= turbo_stream_from "parts" %>
    <%= turbo_frame_tag "parts" do %>
      <%= render @parts %>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>